# Generated by Django 5.2.5 on 2025-08-19 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
