# Generated by Django 5.2.5 on 2025-08-20 17:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing_system', '0002_user_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashed_name', models.CharField(max_length=150, unique=True)),
                ('base_hashed_name', models.CharField(max_length=150)),
                ('webresource_url', models.URLField()),
                ('number_of_scrapes', models.IntegerField(default=0)),
                ('is_automated', models.BooleanField(default=False)),
                ('last_scrape', models.DateTimeField(default=django.utils.timezone.now)),
                ('delay_between_scrapes', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
