# Generated by Django 5.2.5 on 2025-08-20 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing_system', '0003_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='name',
            field=models.CharField(default='lol', max_length=100),
            preserve_default=False,
        ),
    ]
