# Generated by Django 5.2.5 on 2025-08-27 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsing_system', '0004_template_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='scraping_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='template',
            name='scraping_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='template',
            name='scraping_progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='template',
            name='scraping_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='template',
            name='scraping_status',
            field=models.CharField(choices=[('idle', 'Idle'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='idle', max_length=20),
        ),
    ]
